<?php

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Storage;

// ── Authenticated API routes ──────────────────────────────────────────────────
Route::middleware('auth')->group(function () {

    // Image upload for report elements
    Route::post('/upload-image', function (Request $request) {
        $request->validate([
            'image' => 'required|image|mimes:jpeg,png,jpg,gif,webp,svg|max:5120',
        ]);

        try {
            $path = $request->file('image')->store('report-images', 'public');

            return response()->json([
                'url'     => Storage::url($path),
                'path'    => $path,
                'message' => 'Image uploaded successfully.',
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'error'   => 'Upload failed: ' . $e->getMessage(),
            ], 500);
        }
    });

    // AI content generation stub (wire up Anthropic SDK here)
    Route::post('/ai/generate', function (Request $request) {
        $request->validate([
            'prompt' => 'required|string|max:1000',
            'type'   => 'required|in:text,chart_data,headline,summary',
        ]);

        // TODO: Wire up Anthropic PHP SDK:
        // composer require anthropic-php/client
        // $client = Anthropic::client(config('services.anthropic.key'));
        // $result = $client->messages()->create([...]);

        // Stub response for now
        $stubs = [
            'text'       => 'This is AI-generated placeholder text. Connect the Anthropic PHP SDK to enable real generation.',
            'headline'   => 'AI-Powered Report Headline',
            'summary'    => 'Executive summary generated by AI.',
            'chart_data' => json_encode([
                'labels' => ['Q1', 'Q2', 'Q3', 'Q4'],
                'values' => [42000, 58000, 61000, 79000],
            ]),
        ];

        return response()->json([
            'result'  => $stubs[$request->type] ?? 'Generated content',
            'message' => 'AI generation stub — wire up Anthropic SDK.',
        ]);
    });

    // Report AI suggestions
    Route::post('/ai/suggest-chart', function (Request $request) {
        return response()->json([
            'labels' => ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun'],
            'values' => [12500, 18200, 15800, 22400, 19600, 28300],
            'title'  => 'Revenue Trend (AI Suggested)',
        ]);
    });
});